FROM python:3.7.0-alpine3.8

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.py

ENV FLASK_RUN_PORT=8000

ENV FLASK_RUN_HOST=0.0.0.0

CMD flask run